app2/urls.py
from django.urls import path
from app2 import views

app_name = 'app2'

urlpatterns=[
    path('Specific/', views.Specific, name='Specific')
]

project6/urls.py
from django.contrib import admin
from django.urls import path, include
from app1 import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('First/', views.First, name='First'),
    path('Second/', views.Second, name= 'Second'),
    path('app2/', include('app2.urls'))
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def First (request):
    return render(request, 'First.html')

def Second (request):
    return render (request, 'Second.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def Specific (request):
    return render (request, 'Specific.html')

templates/First.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h1>First HTML</h1>
<a href="{%url 'Second'%}">Goto Second HTML</a>
<a href="{%url 'app2:Specific'%}">goto SPecific</a>
</body>
</html>

templates/Second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h1>Second HTML</h1>
<a href="{%url 'First'%}">Goto First HTML</a>
<a href="{%url 'app2:Specific'%}">goto Specific</a>
</body>
</html>

templates/Specific.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Specific HTML</h1>
    <a href="{%url 'First'%}">goto first</a>
    <a href="{%url 'Second'%}"> goto Second</a>
</body>
</html>